set -g base-index 1
setw -g pane-base-index 1

# Pane resizing
bind -r k resize-pane -U 5
bind -r j resize-pane -D 5
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5

bind r source-file ~/.tmux.conf
