return {
    kind = {
		Text = "",
		Method = "",
		Function = "",
		Constructor = "",
		Field = "ﰠ",
		Variable = "",
		Class = "ﴯ",
		Interface = "",
		Module = "",
		Property = "ﰠ",
		Unit = "塞",
		Value = "",
		Enum = "",
		Keyword = "",
		Snippet = "",
		Color = "",
		File = "",
		Reference = "",
		Folder = "",
		EnumMember = "",
		Constant = "",
		Struct = "פּ",
		Event = "",
		Operator = "",
		TypeParameter = ""         
    },
    
    diagnostic = {
        default = {
            { name = "Error",icon = " ", color = "Default" },
            { name = "Warn", icon = " ", color = "Default" },
            { name = "Info", icon = " ", color = "Default" },
            { name = "Hint", icon = " ", color = "Default" },
        },

        catppuccin = {
            { name = "Error", icon = "", color = "Default" },
            { name = "Warn",  icon = "", color = "Default" },
            { name = "Info",  icon = "", color = "Default" },
            { name = "Hint",  icon = "", color = "Default" }
        },
    },

    ui = {
        ArrowClosed = "",
        ArrowOpen = "",
        Lock = "",
        Circle = "",
        BigCircle = "",
        BigUnfilledCircle = "",
        Close = "",
        NewFile = "",
        Search = "",
        Lightbulb = "",
        Project = "",
        Dashboard = "",
        History = "",
        Comment = "",
        Bug = "",
        Code = "",
        Telescope = "",
        Gear = "",
        Package = "",
        List = "",
        SignIn = "",
        SignOut = "",
        Check = "",
        Fire = "",
        Note = "",
        BookMark = "",
        Pencil = "",
        ChevronRight = "",
        Table = "",
        Calendar = "",
        CloudDownload = "",
    },

    notify = {
        ERROR = "",
        WARN = "",
        INFO = "",
        DEBUG = "",
        TRACE = "✎",
    },
    
}
