-- local ok,null_ls = pcall(require,"null-ls")
-- if not ok then
--     vim.notify("Failed to load null-ls\n\n")
--     return
-- end
--
-- null_ls.setup{
--   sources = {
--     null_ls.builtins.diagnostics.eslint,
--     null_ls.builtins.formatting.prettier,
--   },
--   on_attach = function(client, bufnr)
--     if client.supports_method("textDocument/formatting") then
--       vim.api.nvim_clear_autocmds({
--         group = augroup,
--         buffer = bufnr,
--       })
--       vim.api.nvim_create_autocmd("BufWritePre", {
--         group = augroup,
--         buffer = bufnr,
--         callback = function()
--           vim.lsp.buf.format({ bufnr = bufnr })
--         end,
--       })
--     end
--   end,
-- }
